name: cocuisinage_app_mobile_pro
description: cocuisinage_app_mobile_pro

publish_to: "none"

version: 0.0.6+5

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  responsive_sizer: ^3.1.0
  image_picker: ^0.8.5+3
  auto_size_text: ^3.0.0
  flutter_speed_dial: ^6.0.0
  intl: ^0.17.0
  calendar_timeline: ^1.0.5
  permission_handler: ^8.1.4+2

  dartz: ^0.10.1
  http: ^0.13.4
  shared_preferences: ^2.0.15
  argon_buttons_flutter: ^1.1.0
  flutter_spinkit: ^5.1.0
  top_snackbar_flutter: ^2.1.1
  avatar_glow: ^2.0.2
  pull_to_refresh: ^2.0.0
  geolocator: ^9.0.2

  firebase_core: ^1.21.1
  firebase_messaging: ^13.0.0

  cupertino_icons: ^1.0.2
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon/LauncherIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/profile_icons/
    - assets/icons/
    - assets/images/auth_images/
    - assets/equipe_icons/
    - assets/recette_icons/
    - assets/stock_icons/
    - assets/boutique_icons/
    - assets/commande_icons/
    - assets/reseau_icons/
    - assets/social_media_button/
    - assets/message_icons/
    - assets/haccp_icons/
    - assets/porte_monnaie_icons/
    - assets/liste_de_course_icons/
    - assets/produit_icons/
    - assets/prep_commande_icons/
    - assets/launcher_icon/
    - assets/primary_icons/
    - assets/drawer_icons/
    - assets/forget_password/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 200
